

# https://jekyllrb.com/docs/configuration/#default-configuration

# Site
title: Scaffold Jekyll Empty Gulp (Browser-Sync + Sass)
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Author
author:
  name: test name
  email: test@email.com
  web: http://test.es
  github: TestGitHub
  twitter: TestTwitter
  analytics: "'UA-XXXXXXXX-X'"
  description: > # this means to ignore newlines until "baseurl:"
    Write an awesome description.

# Handling Reading
exclude:
  - README.md
  - LICENSE.txt
  - package.json
  - node_modules
  - gulpfile.js

include:
  - .htaccess

# Markdown
markdown: kramdown
kramdown:
  input:      GFM
  auto_ids:   false

# Gems
#gems:
  #- example-gem

# Permalink
permalink: pretty
  # Options
  # (a) /:month-:day-:year/:title
  # (b) /:categories/:year/:month/:day/:title
  # (c) /:title
  # (d) pretty
